<?php

namespace EcommerceBundle\Repository;

/**
 * AfourniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfourniRepository extends \Doctrine\ORM\EntityRepository
{
}
