<?php

namespace EcommerceBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByFacture($utilisateur)
	{
		$qb = $this->createQueryBuilder('u')
					->select('u')
					->where('u.creepar = :utilisateur')
					->andWhere('u.valider = 1')
					->andWHere('u.reference != 0')
					->orderBy('u.id')
					->setParameter('utilisateur', $utilisateur);
		return $qb->getQuery()->getResult();
	}
}
