<?php

namespace EcommerceBundle\Repository;

/**
 * FournisseurproduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurproduitRepository extends \Doctrine\ORM\EntityRepository
{
}
