<?php

namespace EcommerceBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
	public function findArray($array){
		$qb = $this->createQUeryBuilder('u')
					->select('u')
					->where('u.id IN (:array)')
					->setParameter('array', $array);
		return $qb->getQuery()->getResult();
	}


	// public function findByCategorie($categorie){
	// 	$db = $this->createQUeryBuilder('u')
	// 				->select('u')
	// 				->where('u.categorie = :categorie')
	// 				->andWhere('u.disponible = 1 ')
	// 				->orderBy('u.id')
	// 				->setParameter('categorie', $categorie);
	// 			return $qb->getQuery()->getResult();
	// }


	public function recherche($data){
		$qb = $this->createQUeryBuilder('u')
					->select('u')
					->where('u.libelle like :data')
					->andWhere('u.disponible = true')
					->orderBy('u.id')
					->setParameter('data', $data);
				return $qb->getQuery()->getResult();
	}


}
 