<?php

namespace EcommerceBundle\Repository;

/**
 * QteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QteRepository extends \Doctrine\ORM\EntityRepository
{
}
