<?php

namespace EcommerceBundle\Repository;

/**
 * UnitemesureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitemesureRepository extends \Doctrine\ORM\EntityRepository
{
}
