routingAdminUnitemesure:
        resource: "@EcommerceBundle/Resources/config/routing/routingAdminUnitemesure.yml"
        prefix:   /admin/unitemesure/

routingAdminCommande:
        resource: "@EcommerceBundle/Resources/config/routing/routingAdminCommande.yml"
        prefix:   /admin/commande/

routingAdminCategorie:
        resource: "@EcommerceBundle/Resources/config/routing/routingAdminCategorie.yml"
        prefix:   /admin/categorie/

routingAdminProduits:
    resource: "@EcommerceBundle/Resources/config/routing/routingAdminProduit.yml"
    prefix: /admin/produits/

routingPanier:
    resource: "@EcommerceBundle/Resources/config/routing/routingPanier.yml"
    prefix: /panier

routingProduits:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduits.yml"
    prefix: /

routingCommande:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommande.yml"
    prefix: /
