services:
#    ecommerce.example:
#        class: EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

# setNewFacture:
#       class: EcommerceBundle\Services\getFacture
#       arguments: [@service_container]

    redirectionListener:
      class: EcommerceBundle\Listener\RedirectionListener
      arguments: [@service_container,@session]
      tags:
        - { name: kernel.event_listener, event: kernel.request, mehod: onKernelRequest }

    setNewReference:
       class: EcommerceBundle\Services\getReference
       arguments: [@security.context, @doctrine.orm.entity_manager]
